// <auto-generated />
using System;
using ECommerce.InventoryApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.InventoryApi.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.InventoryApi.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Laptops",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Apple M3 Pro chip, 18GB RAM, 512GB SSD",
                            ImageUrl = "https://placehold.co/300x200?text=MacBook+Pro",
                            IsActive = true,
                            Name = "MacBook Pro 14\"",
                            Price = 1999.99m,
                            Rating = 4.9m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 2,
                            Category = "Laptops",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intel Core i7, 16GB RAM, 512GB NVMe SSD",
                            ImageUrl = "https://placehold.co/300x200?text=Dell+XPS+15",
                            IsActive = true,
                            Name = "Dell XPS 15",
                            Price = 1499.99m,
                            Rating = 4.7m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 3,
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A18 Pro chip, 256GB, Titanium finish",
                            ImageUrl = "https://placehold.co/300x200?text=iPhone+16+Pro",
                            IsActive = true,
                            Name = "iPhone 16 Pro",
                            Price = 1199.99m,
                            Rating = 4.8m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 4,
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Snapdragon 8 Elite, 12GB RAM, 256GB",
                            ImageUrl = "https://placehold.co/300x200?text=Samsung+S25",
                            IsActive = true,
                            Name = "Samsung Galaxy S25",
                            Price = 999.99m,
                            Rating = 4.6m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 5,
                            Category = "Audio",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Industry-leading noise cancellation, 30hr battery",
                            ImageUrl = "https://placehold.co/300x200?text=Sony+WH1000XM5",
                            IsActive = true,
                            Name = "Sony WH-1000XM5",
                            Price = 349.99m,
                            Rating = 4.8m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 6,
                            Category = "Wearables",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "49mm Titanium case, GPS + Cellular",
                            ImageUrl = "https://placehold.co/300x200?text=Apple+Watch+Ultra",
                            IsActive = true,
                            Name = "Apple Watch Ultra 2",
                            Price = 799.99m,
                            Rating = 4.7m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 7,
                            Category = "Tablets",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "M4 chip, Liquid Retina XDR display, 256GB",
                            ImageUrl = "https://placehold.co/300x200?text=iPad+Pro",
                            IsActive = true,
                            Name = "iPad Pro 12.9\"",
                            Price = 1099.99m,
                            Rating = 4.9m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 8,
                            Category = "Monitors",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "27\" UHD IPS, 144Hz, HDR600",
                            ImageUrl = "https://placehold.co/300x200?text=LG+4K+Monitor",
                            IsActive = true,
                            Name = "LG 27\" 4K Monitor",
                            Price = 599.99m,
                            Rating = 4.6m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 9,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Advanced wireless keyboard, multi-device",
                            ImageUrl = "https://placehold.co/300x200?text=MX+Keys",
                            IsActive = true,
                            Name = "Logitech MX Keys",
                            Price = 109.99m,
                            Rating = 4.5m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 10,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ergonomic gaming mouse, 30K DPI sensor",
                            ImageUrl = "https://placehold.co/300x200?text=Razer+Mouse",
                            IsActive = true,
                            Name = "Razer DeathAdder V3",
                            Price = 79.99m,
                            Rating = 4.7m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 11,
                            Category = "Gaming",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "7\" OLED screen, 64GB storage, dock included",
                            ImageUrl = "https://placehold.co/300x200?text=Nintendo+Switch",
                            IsActive = true,
                            Name = "Nintendo Switch OLED",
                            Price = 349.99m,
                            Rating = 4.8m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 12,
                            Category = "Cameras",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "5.3K video, HyperSmooth 7.0, waterproof",
                            ImageUrl = "https://placehold.co/300x200?text=GoPro+Hero13",
                            IsActive = true,
                            Name = "GoPro Hero 13 Black",
                            Price = 399.99m,
                            Rating = 4.6m,
                            Stock = 22
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
